<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="cucumber" failures="1" tests="1" name="Default test" time="12.89" errors="0" timestamp="2024-03-20T14:24:50 EDT">
  <testcase classname="CURD.gitHubFunctions" name="deleteRepo" time="12.006">
    <failure type="java.lang.AssertionError" message="Update data functionality is failing due to :: No such host is known (api.github.com)">
      <![CDATA[java.lang.AssertionError: Update data functionality is failing due to :: No such host is known (api.github.com)
at org.testng.Assert.fail(Assert.java:97)
at Base.ApiHelper.deleteRepo(ApiHelper.java:129)
at CURD.gitHubFunctions.deleteRepo(gitHubFunctions.java:146)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- deleteRepo -->
  <testcase classname="CURD.gitHubFunctions" name="validateGetAllRepoInGetData" time="0.0">
    <ignored/>
  </testcase> <!-- validateGetAllRepoInGetData -->
  <testcase classname="CURD.gitHubFunctions" name="validateSingleRepoInGetData" time="0.0">
    <ignored/>
  </testcase> <!-- validateSingleRepoInGetData -->
  <testcase classname="CURD.gitHubFunctions" name="validateUpdateRepo" time="0.0">
    <ignored/>
  </testcase> <!-- validateUpdateRepo -->
  <testcase classname="CURD.gitHubFunctions" name="validateCreateRepoExistingName" time="0.0">
    <ignored/>
  </testcase> <!-- validateCreateRepoExistingName -->
  <testcase classname="CURD.gitHubFunctions" name="validateSingleRepoWithNonExistingRepoNameInGetData" time="0.0">
    <ignored/>
  </testcase> <!-- validateSingleRepoWithNonExistingRepoNameInGetData -->
  <testcase classname="CURD.gitHubFunctions" name="validateCreateRepo" time="0.0">
    <ignored/>
  </testcase> <!-- validateCreateRepo -->
</testsuite> <!-- Default test -->
